name: build-and-test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: .github/workflows/prepare.sh
      - run: bash scripts/first.sh
      - run: make check